### ISSUE TITLE
Too much Ram consumed.

### ISSUE THREAD

**Issue by rlrahulkanojia** [deepsworld/Yolo5Optimized#1]
Details:

Platform - Nano 4GB
Environment - system install, without docker
FP16, default steps mentioned in repo

Running a yolov5s occupies around 2 GB of memory. Is there a way to reduce memory consumption apart from using int8?

**Comment by deepsworld** [comment]
2 GB or even more of memory usage is expected. I was able to run Yolov5s with dynamic shapes input and batch size of 2 on a similar platform. There could be minor difference in using Torch2TRT vs TensorRT with Pycuda (which you can try) and see if it satisfies your use case. You can also run OS in headless mode(without GUI) to have some extra buffer. Memory usage of models vary greatly depending on number of cuda kernels, cuda streams, size of layers, size of input, etc. If you want to try TensorRT with Pycuda, just need to replace the pytorch pre and post processing with numpy and inference/memory allocations with pycuda. Engine can still be built using torch2trt wrapper. Here's some starting code.
https://gist.github.com/deepsworld/80290cef19f7597f16632a2c98ff0cab

**Comment by rlrahulkanojia** [comment]
Got it and thanks for reference code. Will experiment with suggestions to see if I can achieve required optimization.
